modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Sinytra/ConnectorExtras/issues"

[[mods]]
modId="connectorextras_continuity_compat"
version="${file.jarVersion}"
displayName="Connector Extras Continuity Compat"
authors="Su5eD"
displayURL="https://github.com/Sinytra/ConnectorExtras"
description='''
Fixes Continuity's connected textures for modded blocks 
'''
displayTest = 'IGNORE_ALL_VERSION'
[[dependencies.connectorextras_continuity_compat]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras_continuity_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
