modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Sinytra/ConnectorExtras/issues"

[[mods]]
modId="connectorextras_modmenu_bridge"
version="${file.jarVersion}"
displayName="Connector Extras ModMenu Bridge"
authors="Su5eD"
displayURL="https://github.com/Sinytra/ConnectorExtras"
description='''
Integrates ModMenu the config screen factory with Forge's mod list gui.
'''
displayTest = 'IGNORE_ALL_VERSION'

[[mods]]
modId = "modmenu"
version = "7.2.2"
displayName = "ModMenu (Connector Extras)"
description = '''
Dummy mod provided by Connector Extras to allow mods detecting ModMenu to function as expected.
'''

[[dependencies.connectorextras_modmenu_bridge]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras_modmenu_bridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
